name: hourly-cron
on:
  schedule:
    - cron: '0 * * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call deploy webhook
        run: |
          curl --request GET \
          --url 'https://api.vercel.com/v1/integrations/deploy/prj_jpAioTHNcB14i9HkFlVEWAHVga6g/8AyXF8XVuQ'